-- Local demo only. Do not reuse these passwords anywhere else.
--   admin@fakebank.local            LocalAdmin#2026     role admin
--   merchant.north@fakebank.local   LocalNorth#2026     role user
--   merchant.east@fakebank.local    LocalEast#2026      role user
--
-- Hash algorithm is bcrypt ($2a$), generated by pgcrypto. The login code must
-- verify bcrypt. Re-running this file does not duplicate rows.
--
-- Golden transactions are the 10 rows a human can recompute by hand.
-- The ~5,000-row set comes from scripts/generate_data.py, which must skip
-- existing txn_ref values and must use the same formula as transaction_tb.

BEGIN;

INSERT INTO user_tb (email, display_name, role, password_hash)
VALUES
    (
        'admin@fakebank.local',
        'Local Admin',
        'admin',
        crypt('LocalAdmin#2026', gen_salt('bf', 12))
    ),
    (
        'merchant.north@fakebank.local',
        'North Merchant',
        'user',
        crypt('LocalNorth#2026', gen_salt('bf', 12))
    ),
    (
        'merchant.east@fakebank.local',
        'East Merchant',
        'user',
        crypt('LocalEast#2026', gen_salt('bf', 12))
    )
ON CONFLICT (email) DO NOTHING;

INSERT INTO payment_gateway_tb (code, name, settlement_currency)
VALUES
    ('NSP', 'NorthstarPay', 'USD'),
    ('HFL', 'HarborFlow', 'HKD'),
    ('CDG', 'CedarGate', 'USD')
ON CONFLICT (code) DO NOTHING;

INSERT INTO fee_schedule_tb (
    gateway_id,
    version_code,
    txn_type,
    effective_from,
    effective_to,
    settlement_currency,
    percent_rate,
    fixed_fee,
    min_fee,
    fx_markup_bps,
    failed_attempt_fee,
    refund_returns_percent_fee
)
SELECT
    g.id,
    v.version_code,
    v.txn_type,
    v.effective_from,
    v.effective_to,
    g.settlement_currency,
    v.percent_rate,
    v.fixed_fee,
    v.min_fee,
    v.fx_markup_bps,
    v.failed_attempt_fee,
    FALSE
FROM payment_gateway_tb AS g
JOIN (
    VALUES
        ('NSP', '2025-01', 'payment', DATE '2025-01-01', DATE '2026-03-31', 0.029000, 0.3000, 0.5000, 150, 0.0000),
        ('NSP', '2025-01', 'refund',  DATE '2025-01-01', DATE '2026-03-31', 0.000000, 0.3000, 0.0000, 150, 0.0000),
        ('NSP', '2026-04', 'payment', DATE '2026-04-01', NULL::date,       0.026000, 0.3000, 0.5000, 200, 0.0000),
        ('NSP', '2026-04', 'refund',  DATE '2026-04-01', NULL::date,       0.000000, 0.3000, 0.0000, 200, 0.0000),
        ('HFL', '2025-01', 'payment', DATE '2025-01-01', NULL::date,       0.018000, 0.0000, 0.0000,  80, 0.0000),
        ('HFL', '2025-01', 'refund',  DATE '2025-01-01', NULL::date,       0.000000, 1.0000, 0.0000,  80, 0.0000),
        ('CDG', '2025-01', 'payout',  DATE '2025-01-01', DATE '2026-05-31', 0.005000, 2.0000, 2.0000, 100, 0.2500),
        ('CDG', '2025-01', 'refund',  DATE '2025-01-01', DATE '2026-05-31', 0.000000, 2.0000, 0.0000, 100, 0.0000),
        ('CDG', '2026-06', 'payout',  DATE '2026-06-01', NULL::date,       0.005000, 3.5000, 3.5000, 100, 0.2500),
        ('CDG', '2026-06', 'refund',  DATE '2026-06-01', NULL::date,       0.000000, 3.5000, 0.0000, 100, 0.0000)
) AS v (
    gateway_code,
    version_code,
    txn_type,
    effective_from,
    effective_to,
    percent_rate,
    fixed_fee,
    min_fee,
    fx_markup_bps,
    failed_attempt_fee
) ON v.gateway_code = g.code
ON CONFLICT (gateway_id, version_code, txn_type) DO NOTHING;

INSERT INTO fx_mid_rate_tb (base_currency, quote_currency, as_of_date, mid_rate)
VALUES
    ('EUR', 'USD', DATE '2025-01-01', 1.08000000),
    ('GBP', 'USD', DATE '2025-01-01', 1.27000000),
    ('USD', 'HKD', DATE '2025-01-01', 7.80000000),
    ('EUR', 'HKD', DATE '2025-01-01', 8.42400000),
    ('GBP', 'HKD', DATE '2025-01-01', 9.90600000)
ON CONFLICT (base_currency, quote_currency, as_of_date) DO NOTHING;

INSERT INTO document_tb (
    doc_code,
    gateway_id,
    doc_type,
    version_code,
    title,
    effective_from,
    effective_to,
    source_path
)
SELECT
    d.doc_code,
    g.id,
    d.doc_type,
    d.version_code,
    d.title,
    d.effective_from,
    d.effective_to,
    d.source_path
FROM (
    VALUES
        ('NSP-FEE-2025-01', 'NSP', 'fee_schedule', '2025-01', 'NorthstarPay fee schedule 2025-01', DATE '2025-01-01', DATE '2026-03-31', 'docs/source/northstar/fee-schedule-2025-01.md'),
        ('NSP-FEE-2026-04', 'NSP', 'fee_schedule', '2026-04', 'NorthstarPay fee schedule 2026-04', DATE '2026-04-01', NULL::date, 'docs/source/northstar/fee-schedule-2026-04.md'),
        ('NSP-FX-2025-01', 'NSP', 'fx_rules', '2025-01', 'NorthstarPay FX rules 2025-01', DATE '2025-01-01', DATE '2026-03-31', 'docs/source/northstar/fx-rules-2025-01.md'),
        ('NSP-FX-2026-04', 'NSP', 'fx_rules', '2026-04', 'NorthstarPay FX rules 2026-04', DATE '2026-04-01', NULL::date, 'docs/source/northstar/fx-rules-2026-04.md'),
        ('HFL-FEE-2025-01', 'HFL', 'fee_schedule', '2025-01', 'HarborFlow fee schedule 2025-01', DATE '2025-01-01', NULL::date, 'docs/source/harborflow/fee-schedule-2025-01.md'),
        ('HFL-FX-2025-01', 'HFL', 'fx_rules', '2025-01', 'HarborFlow FX rules 2025-01', DATE '2025-01-01', NULL::date, 'docs/source/harborflow/fx-rules-2025-01.md'),
        ('CDG-FEE-2025-01', 'CDG', 'fee_schedule', '2025-01', 'CedarGate fee schedule 2025-01', DATE '2025-01-01', DATE '2026-05-31', 'docs/source/cedargate/fee-schedule-2025-01.md'),
        ('CDG-FEE-2026-06', 'CDG', 'fee_schedule', '2026-06', 'CedarGate fee schedule 2026-06', DATE '2026-06-01', NULL::date, 'docs/source/cedargate/fee-schedule-2026-06.md'),
        ('CDG-FX-2025-01', 'CDG', 'fx_rules', '2025-01', 'CedarGate FX rules 2025-01', DATE '2025-01-01', NULL::date, 'docs/source/cedargate/fx-rules-2025-01.md')
) AS d (
    doc_code,
    gateway_code,
    doc_type,
    version_code,
    title,
    effective_from,
    effective_to,
    source_path
)
JOIN payment_gateway_tb AS g ON g.code = d.gateway_code
ON CONFLICT (doc_code) DO NOTHING;

INSERT INTO document_tb (
    doc_code,
    gateway_id,
    doc_type,
    version_code,
    title,
    effective_from,
    effective_to,
    source_path
)
VALUES (
    'SOP-RECON-2025-01',
    NULL,
    'reconciliation_sop',
    '2025-01',
    'Reconciliation SOP',
    DATE '2025-01-01',
    NULL,
    'docs/source/shared/reconciliation-sop.md'
)
ON CONFLICT (doc_code) DO NOTHING;

-- Golden set. Hand-check these before trusting the generator.
-- Rounding is half-up to 4 decimal places.
-- NSP-FX-0001 and NSP-VER-0002 are the same EUR 100.00 payment under two versions.
-- Mid stays 1.08 so the only change is the fee schedule.

INSERT INTO transaction_tb (
    txn_ref, gateway_id, fee_schedule_id, owner_user_id, parent_txn_id,
    txn_type, status, occurred_at,
    gross_amount, gross_currency, settlement_currency, settlement_gross,
    mid_rate, fx_markup_bps, applied_fx_rate, fx_markup_amount,
    percent_rate, percent_fee, fixed_fee, min_fee, attempt_fee, min_fee_applied,
    total_fee, expected_net, settled_amount, mismatch_code
)
SELECT
    t.txn_ref, g.id, f.id, u.id, NULL,
    t.txn_type, t.status, t.occurred_at,
    t.gross_amount, t.gross_currency, g.settlement_currency, t.settlement_gross,
    t.mid_rate, t.fx_markup_bps, t.applied_fx_rate, t.fx_markup_amount,
    t.percent_rate, t.percent_fee, t.fixed_fee, t.min_fee, t.attempt_fee, t.min_fee_applied,
    t.total_fee, t.expected_net, t.settled_amount, t.mismatch_code
FROM (
    VALUES
        -- min fee: 1.00 USD * 2.9% + 0.30 = 0.3290, raised to min 0.50
        (
            'NSP-MINFEE-0001', 'NSP', '2025-01', 'payment', 'merchant.north@fakebank.local',
            'payment', 'settled', TIMESTAMPTZ '2026-03-15 04:00:00+00',
            1.0000, 'USD', 1.0000,
            1.00000000, 0, 1.00000000, 0.0000,
            0.029000, 0.0290, 0.3000, 0.5000, 0.0000, TRUE,
            0.5000, 0.5000, 0.5000, NULL
        ),
        -- EUR 100 at mid 1.08, markup 150 bps → applied 1.0638, settlement gross 106.3800
        (
            'NSP-FX-0001', 'NSP', '2025-01', 'payment', 'merchant.north@fakebank.local',
            'payment', 'settled', TIMESTAMPTZ '2026-03-15 04:00:00+00',
            100.0000, 'EUR', 106.3800,
            1.08000000, 150, 1.06380000, 1.6200,
            0.029000, 3.0850, 0.3000, 0.5000, 0.0000, FALSE,
            3.3850, 102.9950, 102.9950, NULL
        ),
        -- same economic trade after 2026-04-01: markup 200 bps, percent 2.60%
        (
            'NSP-VER-0002', 'NSP', '2026-04', 'payment', 'merchant.north@fakebank.local',
            'payment', 'settled', TIMESTAMPTZ '2026-04-02 04:00:00+00',
            100.0000, 'EUR', 105.8400,
            1.08000000, 200, 1.05840000, 2.1600,
            0.026000, 2.7518, 0.3000, 0.5000, 0.0000, FALSE,
            3.0518, 102.7882, 102.7882, NULL
        ),
        (
            'NSP-FAIL-0001', 'NSP', '2025-01', 'payment', 'merchant.north@fakebank.local',
            'payment', 'failed', TIMESTAMPTZ '2026-03-16 04:00:00+00',
            80.0000, 'USD', 0.0000,
            1.00000000, 0, 1.00000000, 0.0000,
            0.000000, 0.0000, 0.0000, 0.0000, 0.0000, FALSE,
            0.0000, 0.0000, 0.0000, NULL
        ),
        -- expected 96.8000, settled 96.3000, variance -0.5000
        (
            'NSP-SHORT-0001', 'NSP', '2025-01', 'payment', 'merchant.east@fakebank.local',
            'payment', 'settled', TIMESTAMPTZ '2026-03-20 04:00:00+00',
            100.0000, 'USD', 100.0000,
            1.00000000, 0, 1.00000000, 0.0000,
            0.029000, 2.9000, 0.3000, 0.5000, 0.0000, FALSE,
            3.2000, 96.8000, 96.3000, 'short_pay'
        ),
        (
            'HFL-PAY-0001', 'HFL', '2025-01', 'payment', 'merchant.north@fakebank.local',
            'payment', 'settled', TIMESTAMPTZ '2026-02-01 04:00:00+00',
            500.0000, 'HKD', 500.0000,
            1.00000000, 0, 1.00000000, 0.0000,
            0.018000, 9.0000, 0.0000, 0.0000, 0.0000, FALSE,
            9.0000, 491.0000, 491.0000, NULL
        ),
        (
            'CDG-FEEHIKE-0001', 'CDG', '2025-01', 'payout', 'merchant.east@fakebank.local',
            'payout', 'settled', TIMESTAMPTZ '2026-05-20 04:00:00+00',
            200.0000, 'USD', 200.0000,
            1.00000000, 0, 1.00000000, 0.0000,
            0.005000, 1.0000, 2.0000, 2.0000, 0.0000, FALSE,
            3.0000, 197.0000, 197.0000, NULL
        ),
        (
            'CDG-FEEHIKE-0002', 'CDG', '2026-06', 'payout', 'merchant.east@fakebank.local',
            'payout', 'settled', TIMESTAMPTZ '2026-06-02 04:00:00+00',
            200.0000, 'USD', 200.0000,
            1.00000000, 0, 1.00000000, 0.0000,
            0.005000, 1.0000, 3.5000, 3.5000, 0.0000, FALSE,
            4.5000, 195.5000, 195.5000, NULL
        ),
        (
            'CDG-FAIL-0001', 'CDG', '2025-01', 'payout', 'merchant.east@fakebank.local',
            'payout', 'failed', TIMESTAMPTZ '2026-05-21 04:00:00+00',
            80.0000, 'USD', 0.0000,
            1.00000000, 0, 1.00000000, 0.0000,
            0.000000, 0.0000, 0.0000, 0.0000, 0.2500, FALSE,
            0.2500, -0.2500, -0.2500, NULL
        )
) AS t (
    txn_ref, gateway_code, version_code, schedule_txn_type, owner_email,
    txn_type, status, occurred_at,
    gross_amount, gross_currency, settlement_gross,
    mid_rate, fx_markup_bps, applied_fx_rate, fx_markup_amount,
    percent_rate, percent_fee, fixed_fee, min_fee, attempt_fee, min_fee_applied,
    total_fee, expected_net, settled_amount, mismatch_code
)
JOIN payment_gateway_tb AS g ON g.code = t.gateway_code
JOIN fee_schedule_tb AS f
    ON f.gateway_id = g.id
    AND f.version_code = t.version_code
    AND f.txn_type = t.schedule_txn_type
JOIN user_tb AS u ON u.email = t.owner_email
ON CONFLICT (txn_ref) DO NOTHING;

INSERT INTO transaction_tb (
    txn_ref, gateway_id, fee_schedule_id, owner_user_id, parent_txn_id,
    txn_type, status, occurred_at,
    gross_amount, gross_currency, settlement_currency, settlement_gross,
    mid_rate, fx_markup_bps, applied_fx_rate, fx_markup_amount,
    percent_rate, percent_fee, fixed_fee, min_fee, attempt_fee, min_fee_applied,
    total_fee, expected_net, settled_amount, mismatch_code
)
SELECT
    'HFL-REFUND-0001',
    g.id,
    f.id,
    u.id,
    parent.id,
    'refund',
    'settled',
    TIMESTAMPTZ '2026-02-03 04:00:00+00',
    -500.0000,
    'HKD',
    'HKD',
    -500.0000,
    1.00000000,
    0,
    1.00000000,
    0.0000,
    0.000000,
    0.0000,
    1.0000,
    0.0000,
    0.0000,
    FALSE,
    1.0000,
    -501.0000,
    -501.0000,
    NULL
FROM payment_gateway_tb AS g
JOIN fee_schedule_tb AS f
    ON f.gateway_id = g.id
    AND f.version_code = '2025-01'
    AND f.txn_type = 'refund'
JOIN user_tb AS u ON u.email = 'merchant.north@fakebank.local'
JOIN transaction_tb AS parent ON parent.txn_ref = 'HFL-PAY-0001'
WHERE g.code = 'HFL'
ON CONFLICT (txn_ref) DO NOTHING;

COMMIT;
