"""recreate document_chunk_tb

Revision ID: 3b3cd446ed01
Revises: 56d895f40dbb
Create Date: 2026-10-03 14:15:22.576830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy.vector


# revision identifiers, used by Alembic.
revision: str = '3b3cd446ed01'
down_revision: Union[str, Sequence[str], None] = '56d895f40dbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("DROP TABLE IF EXISTS document_chunk_tb")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk_tb',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('section_path', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='document_chunk_index_chk'),
    sa.ForeignKeyConstraint(['document_id'], ['document_tb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='document_chunk_index_uq'),
    sa.UniqueConstraint('document_id', 'content_hash', name='document_chunk_hash_uq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunk_tb')
    # ### end Alembic commands ###
