"""create remaining tables

Revision ID: 56d895f40dbb
Revises: c26a5f3cec90
Create Date: 2026-10-01 15:00:38.039847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56d895f40dbb'
down_revision: Union[str, Sequence[str], None] = 'c26a5f3cec90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_mid_rate_tb',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('base_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('quote_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('mid_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("base_currency ~ '^[A-Z]{3}$' AND quote_currency ~ '^[A-Z]{3}$' AND base_currency <> quote_currency", name='fx_mid_rate_ccy_chk'),
    sa.CheckConstraint('mid_rate > 0', name='fx_mid_rate_positive_chk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'quote_currency', 'as_of_date', name='fx_mid_rate_pair_uq')
    )
    op.create_table('document_tb',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('doc_code', sa.Text(), nullable=False),
    sa.Column('gateway_id', sa.BigInteger(), nullable=True),
    sa.Column('doc_type', sa.Text(), nullable=False),
    sa.Column('version_code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(doc_type = 'reconciliation_sop' AND gateway_id IS NULL) OR (doc_type <> 'reconciliation_sop' AND gateway_id IS NOT NULL)", name='document_gateway_chk'),
    sa.CheckConstraint("doc_type IN ('fee_schedule', 'fx_rules', 'reconciliation_sop')", name='document_type_chk'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='document_dates_chk'),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateway_tb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_code'),
    sa.UniqueConstraint('source_path')
    )
    op.create_table('gateway_settlement_tb',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('gateway_id', sa.BigInteger(), nullable=False),
    sa.Column('settlement_ref', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('currency', sa.CHAR(length=3), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name='gateway_settlement_ccy_chk'),
    sa.CheckConstraint("status IN ('open', 'paid')", name='gateway_settlement_status_chk'),
    sa.CheckConstraint('period_end >= period_start', name='gateway_settlement_period_chk'),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateway_tb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_ref')
    )
    op.create_table('document_chunk_tb',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_path', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('chunk_index >= 0', name='document_chunk_index_chk'),
    sa.ForeignKeyConstraint(['document_id'], ['document_tb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='document_chunk_index_uq'),
    sa.UniqueConstraint('document_id', 'content_hash', name='document_chunk_hash_uq')
    )
    op.create_table('transaction_tb',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('txn_ref', sa.Text(), nullable=False),
    sa.Column('gateway_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_schedule_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_user_id', sa.BigInteger(), nullable=False),
    sa.Column('parent_txn_id', sa.BigInteger(), nullable=True),
    sa.Column('settlement_id', sa.BigInteger(), nullable=True),
    sa.Column('txn_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('gross_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('settlement_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('settlement_gross', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('mid_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fx_markup_bps', sa.Integer(), nullable=False),
    sa.Column('applied_fx_rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('fx_markup_amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('percent_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('percent_fee', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('fixed_fee', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('min_fee', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('attempt_fee', sa.Numeric(precision=19, scale=4), server_default='0', nullable=False),
    sa.Column('min_fee_applied', sa.Boolean(), nullable=False),
    sa.Column('total_fee', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('expected_net', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('settled_amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('variance_amount', sa.Numeric(precision=19, scale=4), sa.Computed('settled_amount - expected_net', persisted=True), nullable=True),
    sa.Column('mismatch_flag', sa.Boolean(), sa.Computed('settled_amount IS NOT NULL AND settled_amount IS DISTINCT FROM expected_net', persisted=True), nullable=False),
    sa.Column('mismatch_code', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(txn_type = 'refund' AND parent_txn_id IS NOT NULL) OR (txn_type <> 'refund' AND parent_txn_id IS NULL)", name='transaction_refund_parent_chk'),
    sa.CheckConstraint("gross_currency ~ '^[A-Z]{3}$' AND settlement_currency ~ '^[A-Z]{3}$'", name='transaction_ccy_chk'),
    sa.CheckConstraint("mismatch_code IS NULL OR mismatch_code IN ('short_pay', 'fee_drift', 'fx_rate_drift')", name='transaction_mismatch_code_chk'),
    sa.CheckConstraint("status = 'failed' OR gross_currency <> settlement_currency OR (mid_rate = 1 AND applied_fx_rate = 1 AND fx_markup_bps = 0 AND fx_markup_amount = 0 AND settlement_gross = gross_amount)", name='transaction_same_ccy_chk'),
    sa.CheckConstraint("status IN ('pending', 'settled', 'failed')", name='transaction_status_chk'),
    sa.CheckConstraint("txn_type IN ('payment', 'refund', 'payout')", name='transaction_type_chk'),
    sa.CheckConstraint('(settled_amount IS NULL AND mismatch_code IS NULL) OR (settled_amount IS NOT NULL AND settled_amount = expected_net AND mismatch_code IS NULL) OR (settled_amount IS NOT NULL AND settled_amount <> expected_net AND mismatch_code IS NOT NULL)', name='transaction_mismatch_pair_chk'),
    sa.CheckConstraint('expected_net = settlement_gross - total_fee', name='transaction_expected_net_chk'),
    sa.CheckConstraint('gross_amount <> 0', name='transaction_gross_nonzero_chk'),
    sa.CheckConstraint('min_fee_applied = ((percent_fee + fixed_fee) < min_fee)', name='transaction_min_flag_chk'),
    sa.CheckConstraint('percent_fee >= 0 AND fixed_fee >= 0 AND min_fee >= 0 AND attempt_fee >= 0 AND total_fee >= 0 AND fx_markup_amount >= 0 AND percent_rate >= 0 AND fx_markup_bps >= 0 AND mid_rate > 0 AND applied_fx_rate > 0', name='transaction_money_nonneg_chk'),
    sa.CheckConstraint('total_fee = GREATEST(percent_fee + fixed_fee, min_fee) + attempt_fee', name='transaction_total_fee_chk'),
    sa.ForeignKeyConstraint(['fee_schedule_id'], ['fee_schedule_tb.id'], ),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateway_tb.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['user_tb.id'], ),
    sa.ForeignKeyConstraint(['parent_txn_id'], ['transaction_tb.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['gateway_settlement_tb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('txn_ref')
    )
    op.create_index('transaction_gateway_time_idx', 'transaction_tb', ['gateway_id', sa.literal_column('occurred_at DESC')], unique=False)
    op.create_index('transaction_mismatch_idx', 'transaction_tb', ['gateway_id', 'occurred_at'], unique=False, postgresql_where=sa.text('mismatch_flag'))
    op.create_index('transaction_owner_time_idx', 'transaction_tb', ['owner_user_id', sa.literal_column('occurred_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('transaction_owner_time_idx', table_name='transaction_tb')
    op.drop_index('transaction_mismatch_idx', table_name='transaction_tb', postgresql_where=sa.text('mismatch_flag'))
    op.drop_index('transaction_gateway_time_idx', table_name='transaction_tb')
    op.drop_table('transaction_tb')
    op.drop_table('document_chunk_tb')
    op.drop_table('gateway_settlement_tb')
    op.drop_table('document_tb')
    op.drop_table('fx_mid_rate_tb')
    # ### end Alembic commands ###
