"""create fee_schedule_tb

Revision ID: c26a5f3cec90
Revises: ba0117463ab7
Create Date: 2026-10-01 14:36:27.458766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c26a5f3cec90'
down_revision: Union[str, Sequence[str], None] = 'ba0117463ab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_schedule_tb',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('gateway_id', sa.BigInteger(), nullable=False),
    sa.Column('version_code', sa.Text(), nullable=False),
    sa.Column('txn_type', sa.Text(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('settlement_currency', sa.CHAR(length=3), nullable=False),
    sa.Column('percent_rate', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('fixed_fee', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('min_fee', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('fx_markup_bps', sa.Integer(), nullable=False),
    sa.Column('failed_attempt_fee', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('refund_returns_percent_fee', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("settlement_currency ~ '^[A-Z]{3}$'", name='fee_schedule_ccy_chk'),
    sa.CheckConstraint("txn_type IN ('payment', 'refund', 'payout')", name='fee_schedule_type_chk'),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name='fee_schedule_dates_chk'),
    sa.CheckConstraint('fixed_fee >= 0 AND min_fee >= 0 AND failed_attempt_fee >= 0', name='fee_schedule_money_chk'),
    sa.CheckConstraint('fx_markup_bps BETWEEN 0 AND 1000', name='fee_schedule_bps_chk'),
    sa.CheckConstraint('percent_rate >= 0 AND percent_rate < 1', name='fee_schedule_percent_chk'),
    sa.ForeignKeyConstraint(['gateway_id'], ['payment_gateway_tb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gateway_id', 'version_code', 'txn_type', name='fee_schedule_version_txn_uq')
    )
    op.create_index('fee_schedule_lookup_idx', 'fee_schedule_tb', ['gateway_id', 'txn_type', 'effective_from'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fee_schedule_lookup_idx', table_name='fee_schedule_tb')
    op.drop_table('fee_schedule_tb')
    # ### end Alembic commands ###
